### ISSUE TITLE
Help, I have an error when update eyes.nvim in Nvim IDE (lazyvim)

### ISSUE THREAD

**Issue by itokun99** [amedoeyes/eyes.nvim#2]
Hi, I really like the monochrome theme you created, and I have been using it for almost more than two months now, which I installed in my Lazyvim setup.

However, in the past few days, after your recent update regarding the project restructure, I am unable to run it anymore.

Do you know what could be the issue? Is there any solution? I’ve added the following config for now.

<img width="1140" alt="Screenshot 2024-10-16 at 23 51 26" src="https://github.com/user-attachments/assets/4e6b6ab9-54b9-40c7-92c7-0fe4bd6e4063">

```
return {
  {
    "amedoeyes/eyes.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      pallete = "dark",
      extend = {
        highlights = {
          StatusLine = { bg = "none" },
          StatusLineNC = { bg = "none" },
          TabLine = { bg = "none" },
          Normal = { bg = "none" },
          NormalFloat = { link = "Normal" },
        },
        palette = {
          hex00 = "#202020",
          hex01 = "#404040",
          hex02 = "#505050",
          hex03 = "#606060",
          hex04 = "#707070",
          hex05 = "#808080",
          hex06 = "#909090",
          hex07 = "#A0A0A0",
          hex08 = "#B0B0B0",
          hex09 = "#C0C0C0",
          hex10 = "#FFFFFF",
          hex11 = "#FFFFFF",
          hex12 = "#FFFFFF",
          hex13 = "#FFFFFF",
          hex14 = "#FFFFFF",
          hex15 = "#FFFFFF",
        },
      },
    },
  },
}
```

**Comment by amedoeyes** [comment]
I'm really sorry about that oversight. It should be fixed now.

**Comment by itokun99** [comment]
Thanks, @amedoeyes! It’s working on my machine now. 😄
